### ISSUE TITLE
Dependency on package tk

### ISSUE THREAD

**Issue by marnikow** [gnikit/tkinter-tooltip#4]
When I installed the package I noticed that it depends on `tk`.  I'm guessing that it was intended to be depending on `tkinter` instead. 

Since `tkinter` is part of the Python standard library I would propose to delete the dependency.

For reference: the description of the project `tk` on pypi is "TensorKit is a deep learning helper between Python and C++." ([`tk` on pypi.org](https://pypi.org/project/tk/)).

**Comment by gnikit** [comment]
Good catch. I think I clearly mixed mixed something up when writing the setup.py. I will fix it in the next release.

**Comment by gnikit** [comment]
@marnikow This should hopefully have been fixed now in v1.3.0
