### ISSUE TITLE
tooltip and canvas object

### ISSUE THREAD

**Issue by krolaper** [gnikit/tkinter-tooltip#64]
Hi. how to do this for a canvas object?
```
canvas = Canvas()
test = ImageTk.PhotoImage(Image.open('test.jpg'))
img = canvas.create_image(0, 0, image=test)
```

**Comment by gnikit** [comment]
Have a look at the examples folder, specifically

https://github.com/gnikit/tkinter-tooltip/blob/bb28e423cef71bff4bc93285fc89e85ea861e6e2/examples/color_changer.py#L21-L28
