### ISSUE TITLE
Tooltip text flashes

### ISSUE THREAD

**Issue by GrimPixel** [gnikit/tkinter-tooltip#87]
It may be tried out there: https://codeberg.org/GrimPixel/Quiz_Grid. Texts on the tooltip starting from a newline will flash every a few seconds.

**Comment by gnikit** [comment]
Sorry @GrimPixel but I can't reproduce, repo you posted works fine (excluding the missing/incorrect packages in requirements.txt). Please post a MWE that can reproduce the problem.
