### ISSUE TITLE
Tooltip not visible when parent window has .wm_attributes('-topmost', True)

### ISSUE THREAD

**Issue by erikwachters** [gnikit/tkinter-tooltip#88]
Any chance you can add .wm_attributes('-topmost', True) to the tooltip itself?

**Comment by ilopata1** [comment]
Faced the same problem and I was able to address simply with:

```
ToolTip(b, msg="Hover info").attributes('-topmost',True)
```

**Comment by gnikit** [comment]
I think the solution of @ilopata1 is what you should be doing when you want any widget to be at the top.
Having explicit options for certain attributes, seems confusing to me. It might be worth adding a short example where `.attributes('-topmost',True)` is used.

**Comment by gnikit** [comment]
I am closing this since the expectation of the `Tooltip` widget vs other `tkinter` widgets are the same, i.e. if you want to be topmost you need to use `.attributes('-topmost',True)`. This is one of the reasons why the tooltip itself inherits from the `tkinter.TopLevel` class.
