### ISSUE TITLE
Tooltip quite always not showing in Windows 10 Enterprise

### ISSUE THREAD

**Issue by capisani** [gnikit/tkinter-tooltip#92]
Trying the first basilar example 

```
import tkinter as tk
import tkinter.ttk as ttk
from tktooltip import ToolTip

app = tk.Tk()
b = ttk.Button(app, text="Button")
b.pack()
ToolTip(b, msg="Hover info")
app.mainloop()
```

with Python 3.12.2, tkinter-tooltip 3.0.0 on Windows 10 Enterprise, tooltips are not displayed in most cases. Sometimes, they appear in random attempts.

**Comment by gnikit** [comment]
I can't reproduce on my local dev environments and with multiple versions of python 3.10-3.12. Have you tried narrowing this down by using other versions of Python or OSs?
I will be converting this to a Q&A discussion.
